# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Code Club"
  url = "codeclub/"
  weight = 20
  identifier = "codeclub"

[[main]]
  name = "- <b>Schedule</b>"
  url = "codeclub-schedule/"
  weight = 20
  parent = "codeclub"

[[main]]
  name = "- Past Sessions"
  url = "codeclub-schedule/#previous-semesters"
  weight = 30
  parent = "codeclub"

[[main]]
  name = "- Computer Setup"
  url = "codeclub-setup/"
  weight = 40
  parent = "codeclub"

[[main]]
  name = "------------------------"
  url = ""
  weight = 50
  parent = "codeclub"

[[main]]
  name = "- Suggest a Topic"
  url = "codeclub-suggest/"
  weight = 60
  parent = "codeclub"

[[main]]
  name = "-----------------------"
  url = ""
  weight = 75
  parent = "codeclub"

[[main]]
  name = "- <b>About Code Club & Join Us!</b>"
  url = "codeclub-about/"
  weight = 80
  parent = "codeclub"

[[main]]
  name = "Tutorials & Resources"
  url = "material/"
  weight = 50
  identifier = "tutorials"

[[main]]
  name = "AWS Workshop (Feb '23)"
  url = "events/2023-02_aws/"
  weight = 10
  parent = "tutorials"

[[main]]
  name = "---------------------"
  url = ""
  weight = 15
  parent = "tutorials"

[[main]]
  name = "- R Resources and Tips"
  url = "tutorials/r-resources-tips/"
  weight = 20
  parent = "tutorials"

[[main]]
  name = "--------------------"
  url = ""
  weight = 25
  parent = "tutorials"

[[main]]
  name = "- Metabarcoding workshop (Fall '20)"
  url = "https://mcic-osu.github.io/2020-12-microbiomics-workshop/"
  weight = 30
  parent = "tutorials"

[[main]]
  name = "- RNA-seq intro meetings (Spring '21)"
  url = "tutorials/2021-01_rnaseq/"
  weight = 40
  parent = "tutorials"

[[main]]
  name = "- Computing Course (Spring '21)"
  url = "https://mcic-osu.github.io/pracs-sp21/"
  weight = 50
  parent = "tutorials"

[[main]]
  name = "- Command-line, shell scripting and OSC Workshop (Summer '22)"
  url = "https://mcic-osu.github.io/cl-workshop-22/"
  weight = 60
  parent = "tutorials"

[[main]]
  name = "- Ag Genomics Lecture: Command-line computing (Apr '23)"
  url = "tutorials/2023-04_aggenomics/presentation.html"
  weight = 70
  parent = "tutorials"

[[main]]
  name = "Bioinformatics Support"
  url = "support/"
  weight = 60

[[main]]
  name = "About"
  url = "about/"
  weight = 80

[[main]]
  identifier = "github"
  pre = "<i class='fab fa-github'></i>"
  url = "https://github.com/biodash/biodash.github.io"
  weight = 90

[[main]]
  identifier = "rss"
  pre = "<i class='fas fa-rss'></i>"
  url = "https://biodash.github.io/index.xml"
  weight = 100


#[[main]]
#  name = "Courses"
#  url = "courses/"
#  weight = 50
