---
title: "Code Club -- Intro to Session 1"
author: "Jelmer Poelstra, Jessica Cooperstone, Michael Broe, Mike Sovic, Stephen Opiyo"
date: "11/20/2020"
output:
  ioslides_presentation:
    widescreen: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Organizer Introductions

- Jelmer Poelstra (MCIC)
- Jessica Cooperstone (HCS/FST)
- Michael Broe (EEOB)
- Mike Sovic (CAPS)
- Stephen Opiyo (MCIC)

## Sessions

- 1 session per week

- Currently doing each session twice: **Wed 5 pm** & **Fri 3 pm**

- Break next week, three more sessions in December

- Schedule: https://biodash.github.io/codeclub-schedule/

<br>

- **We will poll you for Spring semester time**

## This is experimental -- we need your input

- General feedback welcome during or after sessions

- Please ask questions whenever you are not following!

## The general idea

- Ongoing exposure & practice

- Highly interactive

- Informal and maybe even fun

- We welcome participants to (co-)present a session!

## Session structure

- **Intro**: Up to 20 min.
- **Breakout rooms**: At least 20 min.
- **Recap**: Up to 20 min.

<br>

- Generally some introductory homework and bonus material too.
- We'll send out emails when we put up material for the upcoming session.

<br>

- *Today: much longer intro*

## Zoom guidelines

- Questions: unmute or chat

- Camera on helps!

- Communication using icons under "Participants" menu:
  - `raise hand` -- if you want someone to check in on you
  - `go slower` -- if the presenter is going to fast
  - We will probably not grant requests for coffee breaks :(

## Breakout room guidelines

- Introduce yourself to your room mates

- Camera on helps even more here

- Have someone share their screen

- Try to engage whatever your level,
  and be friendly and patient

- Try to keep everyone aboard

- `ask for help` will alert us (`raise hand` won't!)

## Polling question: working at OSC or locally?

<br>

- **Please open <https://class.osc.edu> even if you want to work locally.**

<br><br>

- If you have problems with your local R/Rstudio,
  best to switch to OSC for the time being.

- (Instructions to update R:   
  https://biodash.github.io/codeclub-novice/#updating-r)

## Today

- Today's session: <https://biodash.github.io/codeclub/01_backyard-birds/>

- Will run through first steps *together*

- Show website layout
