---
title: "Session 2: dplyr core verbs"
subtitle: "Using select, filter, mutate, arrange, and summarize"
summary: "During this second session of Code Club, we will be learning how to use some of the most popular dplyr one-table functions, including filter, select, mutate, arrange, and summarize."  
authors: [jessica-cooperstone]
date: 2020-11-25
output: hugodown::md_document

image: 
  caption: "Artwork by @allison_horst"
  focal_point: ""
  preview_only: false

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>
<br>
<br>

-----

## Prep homework {#prep}


#### Basic computer setup

If you didn't already do this, please follow the [Code Club Computer Setup](/codeclub-setup/) instructions.


#### Test if it works

Please open RStudio locally or [start an OSC RStudio Server session](/codeclub-setup/#osc-run-rstudio).

**Nov 19 addition: If you're working locally, test if you can load the *tidyverse* package
with `library("tidyverse")` inside R.** (If you haven't installed the *tidyverse* yet,
please go to the [Code Club Computer Setup](/codeclub-setup/#install-tidy) instructions.)

If you have not used RStudio before, take a moment to explore what's in the panels and tabs.
(It may help to check out [Mike Sovic's 1-minute intro to the RStudio interface](https://www.youtube.com/watch?v=ByxF3xjN2JQ&list=PLxhIMi78eQegFm3XqsylVa-Lm7nfiUshe&t=2m15s) 
or [RStudio's 3-minute intro](https://fast.wistia.net/embed/iframe/520zbd3tij?videoFoam=true).)

If you're able to do so, please open RStudio again a bit before Code Club starts --
and in case you run into issues,
please join the Zoom call early and we'll troubleshoot.

#### New to R?

If you're completely new to R,
it will be useful to have a look at some of the resources listed on our
[New to R?](/codeclub-novice/) page prior to Code Club.

#### New to dplyr?

If you've never used `dplyr` before (or even if you have), you may find [this cheat sheet](https://github.com/rstudio/cheatsheets/blob/master/data-transformation.pdf) useful.

<br>

----

#### Download today's R script
```{r, eval = FALSE}
todays_R_script <- 'https://raw.githubusercontent.com/biodash/biodash.github.io/master/content/codeclub/02_dplyr-core-verbs/2_Dplyr_one-table_verbs.R'

download.file(todays_R_script)
```

