---
title: |
  | No coronavirus detected
  | in sequences from human nose swab samples
pagetitle: "corona blast"
author: "Jelmer Poelstra (poelstra.1@osu.edu), MCIC Wooster"
date: "`r Sys.Date()`"
output:
  html_document:
    keep_md: yes
    toc: true
    toc_float: true
    fig_caption: true
    code_folding: hide
---

## Summary
RNA-seq data derived from four human nose swabs was examined for the presence of
sequences of coronavirus *SARS-CoV-2*, and none were detected.

<br/>

## Background
Paired-end Illumina iSeq 100 sequences from 4 samples were received from Annika Diaz
(Vlasova lab, Department of Veterinary Preventive Medicine). The samples were derived
from human nose swab cDNA, with each sample representing a different patient.

The objective was to determine whether sequences derived from the coronavirus
*SARS-CoV-2* could be detected.

<br/>

## About this document
This document briefly presents the methods and results of the analysis performed.
It also contains the code that was run (in a `bash` shell on `Ubuntu 20.04`),
and this code can be shown by clicking the `Code` boxes below (or all code can be
shown by clicking the `Code` box at the top). 
Along with this document, I've sent a zipped folder that has the same
directory structure as referred to below in the text and code.

<br/>

## Overview of the methods
- I performed quality control on the 8 `.fastq` files using the software
`fastqc`, and did a filtering and trimming step using
`Trimmomatic` .
- The remaining sequences were classified by source organism using the online tool `Taxonomer`.
- Sequences inferred to be of viral origin by `Taxonomer` were also aligned to NCBI's coronavirus database using `BLAST`.

<br/>

## Raw data
